### ISSUE TITLE
[User Story] Printable question paper

### ISSUE THREAD

**Issue by vivekkant** [deb-sandeep/JoveNotesWebApp#18]
## Story

As a tutor user I wish to print a question paper for a chapter so that I can give it to the student for offline completion.
## Description

There are several cases where the student is expected to write the answers to the question to have both practice of writing as well as improving recall. As an example the English literature such as creative writing is best practised in written form. However once child practices writing these questions the subsequent practice of recall can be done on-line.

For this purpose if a button is available in the notes view, pressing which a pop-up is shows that contains only all the questions of a chapter with blank spaces for answers. This pop-up should be in printable format so that it can be printed.

**Comment by deb-sandeep** [comment]
A very useful feature
