### ISSUE TITLE
Dashboard API optimization - Fetching only non-hidden chapters

### ISSUE THREAD

**Issue by deb-sandeep** [deb-sandeep/JoveNotesWebApp#34]
### Driver

Dashboard load time optimization
### Current situation

In the current implementation, the Dashboard API returns all the user entitled chapters. The UI then decides on the visibility of chapters based on criteria such as the hidden flag. This causes redundant processing, including multiple canvas renderings of hidden elements which can be shunted for optimization.
### Suggested change

Have the Dashboard API return only those chapters which are not-hidden. When the user chooses to make the hidden chapters visible, fetch the hidden chapters via a separate API call. (_Same API with parametrized requests_).

**Comment by vivekkant** [comment]
Good change suggested. I agree with the parametrized approach for filtering.
